#!/usr/bin/env php
<?php

declare(strict_types=1);

use yii\console\Application;

/**
 * Yii console bootstrap file.
 *
 * @see https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */
defined('YII_DEBUG') || define('YII_DEBUG', true);
defined('YII_ENV') || define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new Application($config);
$exitCode = $application->run();
exit($exitCode);
